
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'silver'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'spark'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  silver:
    +materialized: incremental
    +incremental_strategy: merge
    +file_format: delta
    +pre_hook:
      - SET spark.hadoop.fs.s3a.endpoint=http://minio:9000
      - SET spark.hadoop.fs.s3a.access.key=minio
      - SET spark.hadoop.fs.s3a.secret.key=minio123
      - SET spark.hadoop.fs.s3a.path.style.access=true
      - SET spark.hadoop.fs.s3a.connection.ssl.enabled=false
      - SET spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
    silver:
      +location_root: s3a://warehouse/silver
    gold:
      +location_root: s3a://warehouse/gold